# chapter 12 : advanced python

# walrus operator
m=[1,2,3,4,5]
if (n:=len(m)) > 3:
    print(f"list of numbers {m} is too long, must be <= 3")

# type definitions in python

n:int=5 # confirms n is always an int
name:str="sam" # confirms name is always str, in similar way, float, none, and bool can be initialized

def sum(a:int, b:int) -> int: #the arrow with int confirms that the output of this def mthod will always be int
    return a+b
print(sum(9, 7))

# typing library

from typing import List, Tuple, Dict, Union

l:List[int] =[1,2,3,3,5]
t:Tuple[int, str]=(43, "sam")
d:Dict[str, int] = {"rick":45, "nick":46}
u:Union[str, int] = "id567"
u1:Union[str, int] = 456890

# so one can introduce print function and present respective values

# match case

def httpstatus(userinput):
    match userinput:
        case 200:
            print("ok")
        case 404:
            print("not found")
        case 500:
            print("internal server error")
        case _: # default case
            print("unknown")

userinput=int(input("Enter a http status code : "))
httpstatus(userinput)

# dict merger

d1={"a":1, "b":2}
d2={"b":3, "c":4}
merged=d1|d2 # 2 dicts can be merged and if same key has two different values : it will take the value mentuoned in second dict
merged1=d2|d1
print(merged)

print(merged1) # irrespective of whatever value the second dict has, that will get print if the keys are same in both dicts

with (open("file1.txt")as f1 , open("file2.txt")as f2):

# multiple files can be opened using with statement

# try and except

    a=int(input("enter a number: "))
    print(a) # if i put any string here , it will showcase as Valueerror and the next lines in program will not be executed
    print("thank you") # this will not get printed

# so introducing try and except

try:
    a=int(input("enter a number: "))
    print(a)
except ValueError as v:
    print("try inputting an int")
    print(v)
except Exception as e: # here even if error comes, the next line in program will get exevuted but will flash the error
    print("try inputting an int")
    print(e)

print("thankyou statement post try and except")

# raising exceptions

a=int(input("enter first number: "))
b=int(input("enter second number: "))
print("division of first by second : ", a/b)
# but what if b is zero?then error will be thrown and remaining program will be inexeutable

# so raising exceptions

a=int(input("enter first number: "))
b=int(input("enter second number: "))
if (b==0):
    raise ZeroDivisionError("hey second number must not be zero")
else:
    print("division of first by second : ", a/b)
# by raising an excpetion means : u already know what kind of errors can get generated by wrong inputs and u can provide custom error messages

# try with else , try with finally

try:
    a=int(input("enter a num: "))
    print(a)
except Exception as e:
    print(e)
else: # else runs onlt if try block is successful
    print("inside else block")

def main():
    try:
        a=int(input("enter a num: "))
        print(a)
        return
    except Exception as e:
        print(e)
        return
    finally:
        print("inside finally block") # finally block is only necessary when inside a method, because even if try fails or except fails, one returns the code block causing next code block to not run : so use finally, even if return statement is present in try and except : the finally block will run


# name and main module call

def myfunc():
    a=9
    print(a)
myfunc()
print(__name__) # this will print __main__ as its running in same code

# else one can import the myfunc code as: from module import myfunc which will import the code related to myfunc

# also one can use if clause for the module check

if __name__ == "__main__":
    main() # this indicates that if module is run djrectly oe not, if directly theneun the main function....just as we are dojng it here
    
# global and local variables

b=89 # automatic global

def main():
    a=6 # local variable for the method, and for this if automatic global variable is mentioned then that variable will be given preferance over this
    b=3 # even if automatic global is already mentioned : if one mentioned global : then that variable value will be given priority
    print (a, b)
main()

# enumerate : use this if u want to pass two items at once in for loop and both getting incremented simultaneously

l=[1,345,677,865,322]
for index, item in enumerate(l):
    print (f"item at index{index} is {item}")


# list comprehensions

l = [1,2,3,4,5, 6]
squaredlist=[i*i for i in l] # rather than using for loop , initializing empty list and then incrementing index separately might cause too much line overloading, rather this simple one line can save memory space and runtime 
print(squaredlist)